# Site Specific Configuration
name: Gdzie (dzisiaj) pływamy?
description: nie lubisz jak aktywiści klimatyczni blokują ulice bo nie możesz dojechać do pracy?
url: https://gdzieplywamy.pl/
author: AKwiatkowski
timezone: Europe/Warsaw
timezone_short: CET

# Keywords
keywords: ['seo', 'key', 'words']

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 20
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Wpisy w kategorii :cat'
    permalink: '/kategoria/:cat'
    silent: false

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
